#!/bin/bash

echo "$@"
if [[ -n "$@" ]]; then
	ARGS="$@"
else
	ARGS="-s 3"
fi

echo "--> python puzzle_generator.py $ARGS"

python puzzle_generator.py $ARGS > ze_test.board
cat ze_test.board
node --max_old_space_size=16000 input.js ze_test.board
